packages:
  - .
  - examples

catalogMode: strict

catalogs:
  dev:
    '@ai-sdk/openai': ^2.0.80
    '@ai-sdk/provider-utils': ^3.0.18
    '@biomejs/biome': ^1.5.3
    '@hono/mcp': ^0.1.4
    '@types/json-schema': ^7.0.15
    '@types/node': ^22.13.5
    '@typescript/native-preview': ^7.0.0-dev.20251202.1
    '@vitest/coverage-v8': ^3.2.4
    hono: ^4.9.10
    knip: ^5.72.0
    lefthook: ^2.0.8
    msw: ^2.10.4
    publint: ^0.3.12
    tsdown: ^0.15.9
    type-fest: ^4.41.0
    typescript: ^5.8.3
    unplugin-unused: ^0.5.4
    vitest: ^3.2.4
    zod: ^4.1.13
  peer:
    ai: ^5.0.108
    openai: ^6.2.0
  prod:
    '@modelcontextprotocol/sdk': ^1.24.3
    '@orama/orama': ^3.1.11
    json-schema: ^0.4.0

enablePrePostScripts: true

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - lefthook
  - msw

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - undici-types@6.21.0
  - chokidar@4.0.3
