packages:
  - .
  - examples

catalogMode: strict

catalogs:
  dev:
    '@ai-sdk/openai': ^3.0.2
    ai: ^6.0.7
    '@fast-check/vitest': ^0.2.0
    '@clack/prompts': ^0.11.0
    '@hono/mcp': ^0.1.4
    '@types/node': ^22.13.5
    '@typescript/native-preview': ^7.0.0-dev.20251209.1
    '@vitest/coverage-v8': ^4.0.15
    hono: ^4.9.10
    knip: ^5.72.0
    lefthook: ^2.0.8
    msw: ^2.10.4
    oxfmt: ^0.18.0
    oxlint: ^1.32.0
    oxlint-tsgolint: ^0.8.6
    publint: ^0.3.12
    tsdown: ^0.17.2
    type-fest: ^4.41.0
    unplugin-unused: ^0.5.4
    vitest: ^4.0.15
    zod: ^4.3.0
  examples:
    '@anthropic-ai/claude-agent-sdk': ^0.1.67
    '@tanstack/ai': ^0.2.0
    '@tanstack/ai-openai': ^0.2.0
  peer:
    '@anthropic-ai/claude-agent-sdk': ^0.1.67
    '@anthropic-ai/sdk': ^0.52.0
    ai: '>=5.0.108 <7.0.0'
    openai: ^6.2.0
    zod: '>=3.25.0 <5'
  prod:
    '@modelcontextprotocol/sdk': ^1.24.3
    '@orama/orama': ^3.1.11
    defu: ^6.1.4

enablePrePostScripts: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@ai-sdk/gateway'
  - '@ai-sdk/openai'
  - '@ai-sdk/provider'
  - '@ai-sdk/provider-utils'
  - '@anthropic-ai/claude-agent-sdk'
  - '@tanstack/ai'
  - '@tanstack/ai-openai'
  - ai

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - msw
  - oxlint

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - undici-types@6.21.0
  - chokidar@4.0.3
