name: 'Setup Nix'
description: 'Install Nix and configure cache'
runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
      with:
        github_access_token: ${{ github.token }}

    - name: Cache Nix store
      uses: nix-community/cache-nix-action@b426b118b6dc86d6952988d396aa7c6b09776d08 # v7
      with:
        primary-key: nix-${{ runner.os }}

    - name: Load Nix development environment
      shell: bash
      run: nix develop --command true
